language: node_js
node_js:
 - "node"
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: jenna.nichols@redfin.com
  api_key:
    secure: Yg/uBTt+PRtukO2no9XiTgA4itVTEmRsU3DHTIXdW1oq+JlDppfC3kFvNUUpgoBD048Udz5BTGoXgDuS+sKDWvL4KaXd5oArRGUDmbc5zVzytzS3r+yFx2g3gWf6w5XrGtMMvf1siZmjBf1ZE3Pm/tkLwpGxt1hpZZHA+1NAk1piE6Hykg0QwHcyvnEXgUWtQGXCmXZOy7ZlPSelBC2jCdbLHjz9cSCWp+zOjlxOb+rXnGs/iYQphrB/Qy2VfzXm/KhHZFTNdF5+wiG0/657ax6FPjnnxWf19908aXVpoboqjDS58KCm/QKr2qWOwYxcS858d4NGqdtajbgObeQ6wFIdD1vQgvot4SELr6ddJ2CyofXFPOULaAF5l66NJzfSlmJuwrytjoh00BXza0rMBsrzBEF2pNui8BUfdPc+t+dY+8Dg7sdmgNwg5H+JIfrmnpxL7pzf7PPZxApRMjZ/AXSO9keZRlmFHrLrDYmf6AW5Xt3ENcU7Bgf54CG/i6TZjcu9JIKqZIsvZeVlnhQo1ViNELAwD7VilA+akWGoBN6eYAlnl5P1ogJu1S5lpJyYHQeCk9GFeJqYPQ9IYoGE4GKCpkkWjMIQvZMPc9cpE2ReWg+HtXHMGy7l/2qX5HRsKWQkXwAPpG0ygvYpZ5/VVvNJMkhbL+5xPZh9vKhzhaM=
    repo: kcjonson/react-native-cascade
    branch: master
    tags: true
