language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  email: jenna.nichols@redfin.com
  api_key:
    secure: f94O1i4qZ69hAaVFb5lSWTIBpHD/cHc38Xf8v0MBa0Wl7hzvXCqK5fgbEulPU3zAYDgXaxaH37U5muw1vaMpI79G9VsVdgXy0xDvN3RrfhoK/qMN7DN9MF8edLDYgM0mhiO5x1Uet0a37BCUxk+gt8aMeZECmbNRzLHOVls3ZR/QVaEx6XZ0NqoUMtfjiPfsQNmGELn6tomLku20HpTbLEblhTmKw5gAlvu8ZrAnCJgyAueJwhJ/rTI6ahK3dy9b/rS8GTKGJBUpOcnM0AYsqcQp3SSeLDaIu4F2tNigtjyHLnG5OGEV3M0Xu7ieSveBxqWsEFgu/b4vxV3jraqnS0+oYBAwuqWQ/ek0du9kY3g0wh1HMlMo3SNlW2geago/fXVDwDDy9fvKhhg9dpzGhCOez9w8c8aRIjsvZAARecQP766ln+gLAuNh4orpb1HB5rxQ6WThV3XDHqDRWS8C/NRGKC5YrVtKKne9KyvZM2ev5zJO3AjOul1rnLjKxrf/kKoEFlSpAfHivzTdD87EwSqYFvPOAterOEQi+mcJ+gsmb7GMmtPxJW7/DsKt+mJ+UGYKYWwP3HxY7qyyt78MKJiYQ1pp7wrsUQ4eHBy0BQkCcXk73qCA41ofELVN3F6KyebZOXwlieVVBiFZ32UdwKBxoRvtZXsB8B/1UROyDGM=
