language: node_js
node_js:
 - "node"
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: jenna.nichols@redfin.com
  api_key:
    secure: TuEyL/MS0+MHb5H3I4dzjvzXwI9Bqam24f2WobdmvBLTJjNbu8Ix+eXsi4Nq+8fIaLz7axSOnWiZU7f9gX5XnOjjsSAFMT4Jp++XHsS8qAojT9OIjscNPEBdugH4x+WQfJcJsSqKZVQGbx2aOcao6vtWwevuj2VRlKHm0GU+l6PSCBIOcDzbMcHLMDClCTKW6X9ECS8ia8AGlW3+Y5546M2/BMR1hno6VxkDbtdC5+gdn6ge0BTVNQ+RrRxvpsZY1C68kjv8k03NAI7Q6Jjzinfq88l5wB5VRKJ75ZF+/TnaeBmvMI7YHPF1O1buyC47KgTIPWb0wd85T91UXb6IFLff7GX/bf1hbqQiwrVLP/HUibcwYePssVfo/Ga6JY4Tu8Gt5HbtD+Kz16O6liPNKQiyqeZ4Fqy3FFRyWOxAYrWj+tlibx8Ac2LK9Gzm75jPxGMxM4XzqT0GwwlPeeCwBOSRnRQ45q33Mj69UBz1lvk4IVTx+1RKjwZZMlEbE5AWHShO7PzdCsRAFk+Ou9pa0/0oPhpZjfCygh5oGNQRLbcVE/oOKPO0//veSIwF/VVOJdn9PXQUT7Y/A7Yvi7jKoAXeYthsaBCsovt3rc0xoKgyt3rf5QpaJUuLQFrAvC/uY86bcRrwdYhGr0ZoP/6NiI7tQcJmt8a4TBrMzQQ4OBY=
  on:
    repo: kcjonson/react-native-cascade
    branch: master
    tags: true
